### ISSUE TITLE
Error: getaddrinfo ENOTFOUND undefined

### ISSUE THREAD

**Issue by backfisch88** [TA2k/ioBroker.toyota#7]
Hallo

bekomme seit der Version 0.2.0 beim Start folgende Fehler:
`<html>
<body>

toyota.0 | 2023-10-22 12:27:05.884 | error | Error: getaddrinfo ENOTFOUND undefined
-- | -- | -- | --
toyota.0 | 2023-10-22 12:27:05.748 | info | starting. Version 0.2.0 in /opt/iobroker/node_modules/iobroker.toyota, node: v18.17.1, js-controller: 5.0.14
toyota.0 | 2023-10-22 12:27:04.889 | debug | Plugin sentry Initialize Plugin (enabled=true)

</body>
</html>`

ist bereits die Debug ausgabe... Adapter bleibt gelb.
Wenn ich auf "Lexus" umstelle kommt wenigstens, dass er keine Autos gefunden hat

`<html>
<body>

toyota.0 | 2023-10-22 12:30:32.901 | info | Found 0 vehicles
-- | -- | -- | --
toyota.0 | 2023-10-22 12:30:32.900 | debug | ""
toyota.0 | 2023-10-22 12:30:32.374 | debug | {"token":"XXXXXXXXXXXX}}
toyota.0 | 2023-10-22 12:30:31.902 | info | Login to Lexus
toyota.0 | 2023-10-22 12:30:31.871 | info | starting. Version 0.2.0 in /opt/iobroker/node_modules/iobroker.toyota, node: v18.17.1, js-controller: 5.0.14
toyota.0 | 2023-10-22 12:30:30.871 | debug | Plugin sentry Initialize Plugin (enabled=true)

</body>
</html>`

vielen dank

**Comment by TA2k** [comment]
danke für den Hinweis ist mit 0.2.1 behoben

**Comment by backfisch88** [comment]
> danke für den Hinweis ist mit 0.2.1 behoben

eh das war schnell :)
Danke

**Comment by backfisch88** [comment]
> > danke für den Hinweis ist mit 0.2.1 behoben
> 
> eh das war schnell :) Danke

läuft wieder! super wow!
